CONTENT_TYPE = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.gif': 'text/gif',
    '.jpeg': 'image/jpeg',
    '.jpg': 'image/jpeg',
    '.tiff': 'image/tiff',
    '.png': 'image/png',
    '.bmp': 'text/bmp',
    '.wav': 'audio/wav',
    '.midi': 'audio/midi',
    '.mp3': 'audio/mpeg',
    '.vqf': 'audio/vqf',
    '.rm': 'audio/x-pn-realaudio',
    '.ra': 'audio/x-realaudio',
    '.avi': 'video/avi',
    '.mpeg': 'video/mpeg',
    '.doc': 'application/msword',
    '.pdf': 'application/pdf',
    '.rtf': 'application/rtf',
    '.zip': 'application/zip',
}